In [82]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [83]:
X,y = load_iris(return_X_y=True)

In [84]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [85]:
X_train , X_test , y_train, y_test = train_test_split(X,y , test_size = 0.2)

## You can compare the X before and After Preprocessing 

In [86]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [87]:
X_train_scaled

array([[-0.77827642, -0.85994275,  0.11813105,  0.31375753],
       [ 1.03635773,  0.04526014,  0.56461061,  0.44494535],
       [ 0.55245529, -0.63364203,  0.78785039,  0.44494535],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.36326007],
       [-1.50413008,  0.72416232, -1.27711758, -1.12930846],
       [-0.77827642,  2.30826739, -1.22130763, -1.3916841 ],
       [ 1.76221139, -0.4073413 ,  1.45756974,  0.8385088 ],
       [ 0.6734309 , -0.85994275,  0.89947028,  0.96969662],
       [-1.02022764,  0.27156087, -1.38873747, -1.26049628],
       [ 1.15733334, -0.63364203,  0.62042056,  0.31375753],
       [ 0.31050407, -0.18104058,  0.50880067,  0.31375753],
       [-0.17339837, -0.18104058,  0.28556089,  0.0513819 ],
       [ 0.18952846, -0.85994275,  0.78785039,  0.57613316],
       [-1.86705691, -0.18104058, -1.44454742, -1.3916841 ],
       [-0.5363252 ,  1.85566594, -1.33292752, -0.99812064],
       [ 0.55245529, -0.85994275,  0.6762305 ,  0.8385088 ],
       [-1.50413008,  1.

## Behind the logic of StandardScaler

In [88]:
import numpy as np

(X_train - np.mean(X_train, axis =0)) / np.std(X_train, axis=0)


array([[-0.77827642, -0.85994275,  0.11813105,  0.31375753],
       [ 1.03635773,  0.04526014,  0.56461061,  0.44494535],
       [ 0.55245529, -0.63364203,  0.78785039,  0.44494535],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.36326007],
       [-1.50413008,  0.72416232, -1.27711758, -1.12930846],
       [-0.77827642,  2.30826739, -1.22130763, -1.3916841 ],
       [ 1.76221139, -0.4073413 ,  1.45756974,  0.8385088 ],
       [ 0.6734309 , -0.85994275,  0.89947028,  0.96969662],
       [-1.02022764,  0.27156087, -1.38873747, -1.26049628],
       [ 1.15733334, -0.63364203,  0.62042056,  0.31375753],
       [ 0.31050407, -0.18104058,  0.50880067,  0.31375753],
       [-0.17339837, -0.18104058,  0.28556089,  0.0513819 ],
       [ 0.18952846, -0.85994275,  0.78785039,  0.57613316],
       [-1.86705691, -0.18104058, -1.44454742, -1.3916841 ],
       [-0.5363252 ,  1.85566594, -1.33292752, -0.99812064],
       [ 0.55245529, -0.85994275,  0.6762305 ,  0.8385088 ],
       [-1.50413008,  1.

- what we are doing with StandardScaler is avobe with numpy both outputs are same

# Min-Max Scaling

In [89]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.transform(X_test)

In [90]:
X_train_Scaled

array([[0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.58333333, 0.45833333,

# Encoding Data Very Important

## OrdinalEncoder

In [91]:
# We use an Encoder to Convert Data from Text to numbers bcz Algorithms work on Numbers not on characters

from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [92]:
data = fetch_openml('car',as_frame=True).frame

/Users/macbookair/Python/sk_learn/env/lib/python3.11/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


In [93]:
data

,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,small,low,P
1,vhigh,vhigh,2,2,small,med,P
2,vhigh,vhigh,2,2,small,high,P
3,vhigh,vhigh,2,2,med,low,P
4,vhigh,vhigh,2,2,med,med,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,med,med,N
1724,low,low,5more,more,med,high,N
1725,low,low,5more,more,big,low,P
1726,low,low,5more,more,big,med,N


- here we can see that safety amd lug_boot columns are not in numerical form to perform ML
- so we will convert this to numeric

## *How do we know on which columns we have to apply encoder or not?*

-  your data should we be in Order for example there is an order in education that fist there is primary educatioin then scendoray and so on same in these columns there is an order small med high low mid high so we use *OrdinalEncoder* here

- for other columns like countries where there is no oder u cannot classify those columns on the bases of order or rank u use another encoder which is called *OneHotEncoder*


In [94]:
columns_to_encode = ['lug_boot','safety']

encoder = OrdinalEncoder(
    categories = [
        ['small','med','big'],
        ['low', 'med','high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [95]:
data

,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,0.0,0.0,P
1,vhigh,vhigh,2,2,0.0,1.0,P
2,vhigh,vhigh,2,2,0.0,2.0,P
3,vhigh,vhigh,2,2,1.0,0.0,P
4,vhigh,vhigh,2,2,1.0,1.0,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,1.0,1.0,N
1724,low,low,5more,more,1.0,2.0,N
1725,low,low,5more,more,2.0,0.0,P
1726,low,low,5more,more,2.0,1.0,N


- now u can see numbers in lug_boot and in safety columns

### We can also inverse the transform

In [96]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

# OneHotEncoder

In [97]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [98]:
data = fetch_openml('adult',as_frame=True).frame

/Users/macbookair/Python/sk_learn/env/lib/python3.11/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


In [99]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K


In [100]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [101]:
encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

encoded_values = encoder.fit_transform(data[['occupation','race']])
new_cols = encoder.get_feature_names_out(['occupation','race'])

In [102]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [103]:
df_encoded = pd.DataFrame(encoded_values , columns = new_cols, index =data.index)
data_final = pd.concat(
    [data.drop(columns=['occupation','race']),df_encoded],
    axis=1
)

In [104]:
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,hoursperweek,native-country,class,occupation_Adm-clerical,occupation_Armed-Forces,occupation_Craft-repair,occupation_Exec-managerial,occupation_Farming-fishing,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,2,United-States,<=50K,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,0,United-States,<=50K,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,2,United-States,<=50K,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,2,United-States,<=50K,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,2,Cuba,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,2,United-States,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,2,United-States,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,3,United-States,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,2,United-States,<=50K,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
